![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [152]:
# We've loaded your first package for you! You can add as many cells as you need.
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

# Begin coding here ...
# importing the files
airbnb_price = pd.read_csv(r"data/airbnb_price.csv", sep = ",")
path = "data/airbnb_room_type.xlsx"
airbnb_room_type = pd.read_excel(path)
airbnb_last_review = pd.read_csv(r"data/airbnb_last_review.tsv", sep = "\t")

In [153]:
# printing the head of first table
print(airbnb_price.head())
print(airbnb_price.info())

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None

In [154]:
# merging the 3 tables
merged_dfs = airbnb_price.merge(airbnb_room_type, on = "listing_id")\
                .merge(airbnb_last_review, on = "listing_id")
print(merged_dfs.head())

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 7 columns]

In [155]:
# What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.
merged_dfs["review_dates"] = pd.to_datetime(merged_dfs["last_review"], format='%B %d %Y')

first_reviewed = merged_dfs["review_dates"].min()
last_reviewed = merged_dfs["review_dates"].max()

# Print the results
print("Earliest review date:", first_reviewed.strftime("%Y-%m-%d"))
print("Most recent review date:", last_reviewed.strftime("%Y-%m-%d"))

Earliest review date: 2019-01-01
Most recent review date: 2019-07-09

In [156]:
# How many of the listings are private rooms? Save this into any variable.

merged_dfs["room_type"] = merged_dfs["room_type"].str.lower()
nb_private_rooms = (merged_dfs["room_type"] == "private room").sum()

print("Number of listings for private room are: ", nb_private_rooms)

Number of listings for private room are:  11356

In [157]:
# What is the average listing price? Round to the nearest penny and save into a variable.
merged_dfs["price"] = merged_dfs["price"].astype(str)
merged_dfs["price"] = merged_dfs["price"].str.strip("dollars")
merged_dfs["price"] = merged_dfs["price"].astype(int)

avg_price = (merged_dfs["price"]).mean().round(2)
print("The average listing price: ", avg_price)

The average listing price:  141.78

In [158]:
# Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. The DataFrame should only contain one row of values.
new_variables_dict = {"first_reviewed" : [first_reviewed],
                   "last_reviewed" : [last_reviewed],
                   "nb_private_rooms" : [nb_private_rooms],
                   "avg_price" : [avg_price]}

review_dates = pd.DataFrame(new_variables_dict)
print(new_variables_df)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78